#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0

START=15
STOP=90
USE_PROCD=1

PROG=/usr/sbin/mwan3evtd

start_service() {
	procd_open_instance mwan3evtd
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /etc/config/mwan3evtd
	procd_close_instance
}

reload_service() {
	if ubus -t 1 call mwan3evtd reload >/dev/null 2>&1; then
		return 0
	fi
	# mwan3evtd not responding; fall back to a restart
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger mwan3evtd
}
